CREATE DATABASE IF NOT EXISTS Web;
USE Web;

CREATE TABLE IF NOT EXISTS UserTable(
	ID VARCHAR(32) NOT NULL UNIQUE,
    UID CHAR(12) NOT NULL UNIQUE,
    `Password` CHAR(128) NOT NULL,
    RegisterationTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Nickname VARCHAR(32) NOT NULL,
    ProfileUrl VARCHAR(128) NOT NULL,
    Permissions VARCHAR(1024) NOT NULL,
    PRIMARY KEY(ID, UID)
);

CREATE TABLE IF NOT EXISTS PostTable(
	ID INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    WriterID CHAR(12) NOT NULL,
    `Name` TEXT NOT NULL,
    Tags TEXT NOT NULL,
    Content TEXT NOT NULL,
    RawContent TEXT NOT NULL,
    WrittenTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedTime TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    FOREIGN KEY(WriterID) REFERENCES UserTable(UID)
);

CREATE TABLE IF NOT EXISTS CommentTable(
	ID INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    PostID INTEGER NOT NULL,
    WriterID CHAR(12) NOT NULL,
    Content TEXT NOT NULL,
    RawContent TEXT NOT NULL,
    WrittenTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedTime TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    FOREIGN KEY(WriterID) REFERENCES UserTable(UID),
    FOREIGN KEY(PostID) REFERENCES PostTable(ID)
);

CREATE TABLE IF NOT EXISTS TokenTable(
    ID CHAR(16) NOT NULL UNIQUE,
    UID CHAR(16) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(UID) REFERENCES UserTable(UID)
);

CREATE USER ':dbuser:'@'localhost' IDENTIFIED WITH mysql_native_password BY ':password:';
GRANT ALL PRIVILEGES ON ':dbname:'.* TO ':dbuser:'@':dbhost:';